# Generated by Django 3.0.4 on 2024-07-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('is_viral', models.CharField(max_length=5)),
                ('gene_name', models.CharField(max_length=50)),
                ('protein_name_true', models.CharField(max_length=100, null=True)),
                ('gene_name_true', models.CharField(max_length=50, null=True)),
                ('uniprot', models.CharField(max_length=10, null=True)),
                ('length', models.IntegerField()),
                ('taxid', models.CharField(max_length=10, null=True)),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViralMutEnrichment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logodds', models.FloatField(null=True)),
                ('ci_lower', models.FloatField(null=True)),
                ('ci_upper', models.FloatField(null=True)),
                ('pvalue', models.FloatField(null=True)),
                ('ires_novar', models.IntegerField()),
                ('ires_var', models.IntegerField()),
                ('noires_var', models.IntegerField()),
                ('noires_novar', models.IntegerField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viralmutenr_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viralmutenr_p2', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='ViralMut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sars_prot', models.CharField(max_length=6)),
                ('covid_pos', models.IntegerField()),
                ('covid_aa', models.CharField(max_length=1)),
                ('sars_pos', models.IntegerField()),
                ('sars_aa', models.CharField(max_length=1)),
                ('prot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viral_mut_prot', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='SingleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=50)),
                ('coverage', models.CharField(max_length=32, null=True)),
                ('pdb_id', models.CharField(max_length=4, null=True)),
                ('chain', models.CharField(max_length=32, null=True)),
                ('modbase_id', models.CharField(max_length=32, null=True)),
                ('sourcedisplay', models.CharField(max_length=50)),
                ('res_range', models.TextField()),
                ('prot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_struct', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='PopVarEnrichment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logodds', models.FloatField(null=True)),
                ('ci_lower', models.FloatField(null=True)),
                ('ci_upper', models.FloatField(null=True)),
                ('pvalue', models.FloatField(null=True)),
                ('ires_novar', models.IntegerField()),
                ('ires_var', models.IntegerField()),
                ('noires_var', models.IntegerField()),
                ('noires_novar', models.IntegerField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popvarenr_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popvarenr_p2', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='PopVar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chrom', models.CharField(max_length=2)),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=1)),
                ('alt', models.CharField(max_length=1)),
                ('rsid', models.CharField(max_length=12, null=True)),
                ('aa_pos', models.IntegerField()),
                ('aa_ref', models.CharField(max_length=1)),
                ('aa_alt', models.CharField(max_length=1)),
                ('sift_category', models.CharField(max_length=26, null=True)),
                ('sift_score', models.FloatField(null=True)),
                ('polyphen_category', models.CharField(max_length=17, null=True)),
                ('polyphen_score', models.FloatField(null=True)),
                ('gnomad_af', models.FloatField(null=True)),
                ('clnsig', models.TextField(null=True)),
                ('somatic', models.CharField(max_length=7, null=True)),
                ('pheno', models.CharField(max_length=7, null=True)),
                ('uniprot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_var_prot', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceSimilarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p2_gene', models.CharField(max_length=20)),
                ('p2_gene_true', models.CharField(max_length=50, null=True)),
                ('p2_protein_true', models.CharField(max_length=100, null=True)),
                ('is_viral', models.CharField(max_length=20)),
                ('interactor', models.CharField(max_length=20)),
                ('interactor_gene', models.CharField(max_length=20)),
                ('interactor_gene_true', models.CharField(max_length=50, null=True)),
                ('interactor_protein_true', models.CharField(max_length=100, null=True)),
                ('similarity', models.FloatField()),
                ('ires', models.TextField(null=True)),
                ('ires_mask', models.TextField(null=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_p2', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('p1_ires', models.TextField(null=True)),
                ('p2_ires', models.TextField(null=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itf_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itf_p2', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('activity_type', models.TextField()),
                ('activity', models.TextField(null=True)),
                ('reference', models.TextField(null=True)),
                ('smiles', models.TextField()),
                ('zinc_id', models.CharField(max_length=20, null=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_p2', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_domain', models.TextField()),
                ('prot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_prot', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='DockedModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt', models.IntegerField()),
                ('file', models.CharField(max_length=40)),
                ('priority', models.IntegerField()),
                ('score', models.FloatField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docked_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docked_p2', to='mainapp.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='DDGSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ddg', models.FloatField()),
                ('ddg_std', models.FloatField()),
                ('pvalue', models.FloatField()),
                ('pdbfile', models.TextField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddg_p1', to='mainapp.Protein')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddg_p2', to='mainapp.Protein')),
            ],
        ),
    ]
