# Generated by Django 3.0.4 on 2024-07-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockedmodel',
            name='file',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interfacesimilarity',
            name='interactor_gene',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interfacesimilarity',
            name='interactor_gene_true',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interfacesimilarity',
            name='interactor_protein_true',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interfacesimilarity',
            name='p2_gene',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interfacesimilarity',
            name='p2_gene_true',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interfacesimilarity',
            name='p2_protein_true',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene_name_true',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protein',
            name='is_viral',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_name_true',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='taxid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='singlemodel',
            name='chain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='singlemodel',
            name='coverage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='singlemodel',
            name='file',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singlemodel',
            name='modbase_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='singlemodel',
            name='pdb_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='singlemodel',
            name='sourcedisplay',
            field=models.CharField(max_length=200),
        ),
    ]
